### ISSUE TITLE
Hugo ?

### ISSUE THREAD

**Issue by johnpapa** [johnpapa/hello-worlds#38] opened 2020-05-22 03:14 UTC
By making a PR you are agreeing to that contributing a hello world project allows the repo/project owner to use the hello world app in examples for their own use.

- [ ] only the most simple basic hello world app
- [ ] must say "Hello World" on the main component
- [ ] only include the minimal components (1 ideally)
- [ ] no routing, not extras whatsoever
- [ ] no styling
- [ ] nothing else !
- [ ] must work by running `npm install` and `npm start` (or equivalent)
- [ ] must be in the folder named `<tech-name>`
- [ ] add yourself using the all-contributors bot `@allcontributors please add @<your-github-account> for code`
- [ ] add build steps and which folder to serve in the README.md, Serve the `public` folder

**Comment by HugoDF** [comment] 2020-05-22 08:02
Is this a dupe of https://github.com/johnpapa/hello-worlds/issues/11?

**Closed as completed** 2020-05-24 03:01 UTC
